/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-10-17 14:26:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hodlogreg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>ANODITE CELL</title>\r\n");
      out.write("      <!--meta tags -->\r\n");
      out.write("      <meta charset=\"UTF-8\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("      <meta name=\"keywords\" content=\"Molten Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("         Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("       \r\n");
      out.write("       <!--//meta tags ends here-->\r\n");
      out.write("      <!--booststrap-->\r\n");
      out.write("      <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("      <!--//booststrap end-->\r\n");
      out.write("      <!-- font-awesome icons -->\r\n");
      out.write("      <link href=\"css/fontawesome-all.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("      <link href=\"css1/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("      <!-- //font-awesome icons -->\r\n");
      out.write("      <!--stylesheets-->\r\n");
      out.write("      <link href=\"css/style.css\" rel='stylesheet' type='text/css' media=\"all\">\r\n");
      out.write("      <!--//stylesheets-->\r\n");
      out.write("      <link href=\"//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("      <link href=\"//fonts.googleapis.com/css?family=Open+Sans:300,400,600\" rel=\"stylesheet\">\r\n");
      out.write("\t  <!--js working-->\r\n");
      out.write("      <script src='js/jquery-2.2.3.min.js'></script>\r\n");
      out.write("      <!--//js working-->\r\n");
      out.write("\t  <!--responsiveslides banner-->\r\n");
      out.write("      <script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("\t  <!--bootstrap working-->\r\n");
      out.write("      <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("      <!-- //bootstrap working-->\r\n");
      out.write("      \r\n");
      out.write("       <script src=\"js/easyResponsiveTabs.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("      <script>\r\n");
      out.write("\t  \r\n");
      out.write("\t  addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }\r\n");
      out.write("\t  \r\n");
      out.write("         $(document).ready(function () {\r\n");
      out.write("         \t$('#horizontalTab').easyResponsiveTabs({\r\n");
      out.write("         \t\ttype: 'default', //Types: default, vertical, accordion           \r\n");
      out.write("         \t\twidth: 'auto', //auto or any width like 600px\r\n");
      out.write("         \t\tfit: '100%' // 100% fit in a container\r\n");
      out.write("         \t});\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         window.onload=function(){getTime();}  \r\n");
      out.write("\r\n");
      out.write(" \t\tfunction getTime()\r\n");
      out.write(" \t\t{  \r\n");
      out.write(" \t\t\tvar today=new Date();  \r\n");
      out.write(" \t\t\tvar h=today.getHours();  \r\n");
      out.write(" \t\t\tvar m=today.getMinutes();  \r\n");
      out.write(" \t\t\tvar s=today.getSeconds();  \r\n");
      out.write("\r\n");
      out.write(" \t\t\t// add a zero in front of numbers<10  \r\n");
      out.write(" \t\t\th=checkTime(h);\r\n");
      out.write(" \t\t\tm=checkTime(m);  \r\n");
      out.write(" \t\t\ts=checkTime(s);  \r\n");
      out.write("\r\n");
      out.write(" \t\t\tdocument.getElementById('clockdisp').innerHTML=h+\":\"+m+\":\"+s;  \r\n");
      out.write("\r\n");
      out.write(" \t\t\t//Recursive Function Call\r\n");
      out.write(" \t\t\tsetTimeout(function(){getTime()},1000);\r\n");
      out.write(" \t\t\t//setInterval(\"getTime()\",1000);//another way\r\n");
      out.write(" \t\t}  \r\n");
      out.write("     \r\n");
      out.write(" \t\tfunction checkTime(i)\r\n");
      out.write(" \t\t{  \r\n");
      out.write(" \t\t\tif (i<10)\r\n");
      out.write(" \t\t\t{  i=\"0\" + i;  }\r\n");
      out.write(" \t\t\treturn i;  \r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t$(document).ready(function(){  \r\n");
      out.write(" \t\t    $(\"#flip\").click(function(){  \r\n");
      out.write(" \t\t        $(\"#panel\").slideToggle(\"slow\");  \r\n");
      out.write(" \t\t    });  \r\n");
      out.write(" \t\t}); \r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction showpassword() \r\n");
      out.write(" \t\t{\r\n");
      out.write(" \t\t    var x = document.getElementById(\"password\");\r\n");
      out.write(" \t\t    if (x.type === \"password\") {\r\n");
      out.write(" \t\t        x.type = \"text\";\r\n");
      out.write(" \t\t    } else {\r\n");
      out.write(" \t\t        x.type = \"password\";\r\n");
      out.write(" \t\t    }\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction showpassword1() \r\n");
      out.write(" \t\t{\r\n");
      out.write(" \t\t    var x = document.getElementById(\"password1\");\r\n");
      out.write(" \t\t    if (x.type === \"password\") {\r\n");
      out.write(" \t\t        x.type = \"text\";\r\n");
      out.write(" \t\t    } else {\r\n");
      out.write(" \t\t        x.type = \"password\";\r\n");
      out.write(" \t\t    }\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t</script>\r\n");
      out.write("\t\r\n");
      out.write(" \t\t<script type=\"text/javascript\">\t\t\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t /*var xmlhttp = new getXMLObject();\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t     function ajaxFunction() \r\n");
      out.write("\t     {\r\n");
      out.write("\t    \tvar email = document.getElementById(\"email1\").value;\r\n");
      out.write("\t    \talert(email);\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t\t\t if(xmlhttp.readyState == 0 || xmlhttp.readyState == 4 )        \r\n");
      out.write("\t         {\r\n");
      out.write("\t    \t\t var email = document.getElementById(\"email1\").value;\r\n");
      out.write("\t    \t\t//alert(email);\r\n");
      out.write("\t    \t\txmlhttp.open(\"GET\",\"checkusername?email=\"+email, true);\r\n");
      out.write("\t            xmlhttp.onreadystatechange  = handleServerResponse;\r\n");
      out.write("\t              //  xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');\r\n");
      out.write("\t            xmlhttp.send(null); \r\n");
      out.write("\t         }\r\n");
      out.write("\t     }\r\n");
      out.write("\t    function handleServerResponse() \r\n");
      out.write("\t     {\r\n");
      out.write("\t    \t \r\n");
      out.write("\t        if (xmlhttp.readyState == 4) \r\n");
      out.write("\t        {\r\n");
      out.write("\t            if(xmlhttp.status == 200) \r\n");
      out.write("\t            {\r\n");
      out.write("\t            \tvar xmlMessage= xmlhttp.responseXML;\r\n");
      out.write("\t            \tvar found = xmlMessage.getElementsByTagName(\"found\")[0].firstChild.nodeValue;\r\n");
      out.write("\t            \t\r\n");
      out.write("\t            \tif(found == \"true\")\r\n");
      out.write("\t            \t{\r\n");
      out.write("\t            \t\tvar validationMessage=document.getElementById(\"validationMessage\");\r\n");
      out.write("\t            \t\tvalidationMessage.innerHTML = \"EMAIL Id PRESENT..TRY OTHER EMAILID\";\r\n");
      out.write("\t            \t\tdocument.getElementById(\"submitForm\").disabled = true;\r\n");
      out.write("\t                }\r\n");
      out.write("\t            \t\r\n");
      out.write("\t            \tif(found == \"false\")\r\n");
      out.write("\t            \t{\r\n");
      out.write("\t            \t\tvar validationMessage=document.getElementById(\"validationMessage\");\r\n");
      out.write("\t            \t\tvalidationMessage.innerHTML = \"EMAIL Id AVALABLE\";\r\n");
      out.write("\t            \t\tdocument.getElementById(\"submitForm\").disabled = false;\r\n");
      out.write("\t            \t}\r\n");
      out.write("\t            }\r\n");
      out.write("\t            \r\n");
      out.write("\t            else \r\n");
      out.write("\t            {\r\n");
      out.write("\t                 alert(\"Error during AJAX call. Please try again\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t     }*/\r\n");
      out.write("</script>\r\n");
      out.write("      \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- //here start HEADER -->\r\n");
      out.write("      <div class=\"header-outs\" id=\"header\">\r\n");
      out.write("         <!--banner -->\r\n");
      out.write("         <div class=\"header-most-top\">\r\n");
      out.write("            <div class=\"one-headder\">\r\n");
      out.write("               <div class=\"container-fluid\">\r\n");
      out.write("                  <div class=\"row left-indus-icons RWDpagescrollfix\">\r\n");
      out.write("                     <div class=\"col-lg-5 col-md-5 col-sm-4 pr-0 icons\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <h4 id=\"clockdisp\"></h4>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-lg-7 col-md-7 col-sm-8 agile-email-call \">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <h4>Call Us:</h4>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <p>7003871310</p>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li >\r\n");
      out.write("                              <h4>Email Us:</h4>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <p><a href=\"mailto:surat.banerjee@gmail.com\">surat.banerjee@gmail.com</a></p>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"headder-nav-icon pagescrollfix\">\r\n");
      out.write("               <div class=\"container-fluid\">\r\n");
      out.write("                  <div class=\"nav-headder-top\">\r\n");
      out.write("                     <!--//navigation section -->\r\n");
      out.write("                     <nav class=\"navbar navbar-expand-lg navbar-light pagescrollfix\">\r\n");
      out.write("                        <div class=\"hedder-up\">\r\n");
      out.write("                           <h1><a class=\"navbar-brand \" href=\"index.jsp\"><span class=\"fa fa-envira\"></span>ANODITE CELL</a></h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarSupportedContent\">\r\n");
      out.write("                           <ul class=\"navbar-nav \">\r\n");
      out.write("                              <li class=\"nav-item active\">\r\n");
      out.write("                                 <a class=\"nav-link\" href=\"index.jsp\">HOME <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"about.jsp\" class=\"nav-link\">ABOUT</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"stafflogreg.jsp\" class=\"nav-link\">STAFF_LOGIN</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"hodlogreg.jsp\" class=\"nav-link\">HOD_LOGIN</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </nav>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"clearfix\"> </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- //Navigation -->\r\n");
      out.write("         <!-- Slideshow 4 -->\r\n");
      out.write("         <div class=\"slider\">\r\n");
      out.write("            <div class=\"callbacks_container\">\r\n");
      out.write("               <ul class=\"rslides\" id=\"slider4\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <div class=\"slider-img one-img\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                           <div class=\"slider-info \">\r\n");
      out.write("                              <h5>College Inventory System</h5>\r\n");
      out.write("                              <div class=\"bottom-info\">\r\n");
      out.write("                                 <p> </p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <div class=\"slider-img two-img\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                           <div class=\"slider-info \">\r\n");
      out.write("                              <h5>Let Work Together</h5>\r\n");
      out.write("                              <div class=\"bottom-info\">\r\n");
      out.write("                                 <p>   </p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <div class=\"slider-img three-img\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                           <div class=\"slider-info\">\r\n");
      out.write("                              <h5>Innovative Project</h5>\r\n");
      out.write("                              <div class=\"bottom-info\">\r\n");
      out.write("                                 <p>   </p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- This is here just to demonstrate the callbacks -->\r\n");
      out.write("            <!-- <ul class=\"events\">\r\n");
      out.write("               <li>Example 4 callback events</li>\r\n");
      out.write("               </ul>-->\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- //banner -->\r\n");
      out.write("\t  \r\n");
      out.write("\t  <script>\r\n");
      out.write("         $(window).scroll(function() {\r\n");
      out.write("             if ($(document).scrollTop() > 150) {\r\n");
      out.write("                 $('nav.pagescrollfix,nav.RWDpagescrollfix').addClass('shrink');\r\n");
      out.write("             } else {\r\n");
      out.write("                 $('nav.pagescrollfix,nav.RWDpagescrollfix').removeClass('shrink');\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("      </script>\r\n");
      out.write("\t  <!--//Nav script scrollon--> \r\n");
      out.write("      <script>\r\n");
      out.write("         // You can also use \"$(window).load(function() {\"\r\n");
      out.write("         $(function () {\r\n");
      out.write("         \t// Slideshow 4\r\n");
      out.write("         \t$(\"#slider4\").responsiveSlides({\r\n");
      out.write("         \t\tauto: true,\r\n");
      out.write("         \t\tpager:true ,\r\n");
      out.write("         \t\tnav:false,\r\n");
      out.write("         \t\tspeed: 900,\r\n");
      out.write("         \t\tnamespace: \"callbacks\",\r\n");
      out.write("         \t\tbefore: function () {\r\n");
      out.write("         \t\t\t$('.events').append(\"<li>before event fired.</li>\");\r\n");
      out.write("         \t\t},\r\n");
      out.write("         \t\tafter: function () {\r\n");
      out.write("         \t\t\t$('.events').append(\"<li>after event fired.</li>\");\r\n");
      out.write("         \t\t}\r\n");
      out.write("         \t});\r\n");
      out.write("         \r\n");
      out.write("         });\r\n");
      out.write("      </script>\r\n");
      out.write("      <!--// responsiveslides banner-->\t\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- start-smoth-scrolling -->\r\n");
      out.write("      <!-- here stars scrolling icon -->\r\n");
      out.write("      <script>\r\n");
      out.write("         $(document).ready(function () {\r\n");
      out.write("         \r\n");
      out.write("         \tvar defaults = {\r\n");
      out.write("         \t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("         \t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("         \t\tscrollSpeed: 1100,\r\n");
      out.write("         \t\teasingType: 'linear'\r\n");
      out.write("         \t};\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \t$().UItoTop({\r\n");
      out.write("         \t\teasingType: 'easeOutQuart'\r\n");
      out.write("         \t});\r\n");
      out.write("         \r\n");
      out.write("         });\r\n");
      out.write("      </script>\r\n");
      out.write("      <!-- //here ends scrolling icon -->\r\n");
      out.write(" <!-- //here ends HEADER -->\r\n");
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t <!-- LOGIN & REGISTRATION AREA -->\r\n");
      out.write("\t \r\n");
      out.write("\t <!-- short -->\r\n");
      out.write("      <div class=\"using-border py-3\">\r\n");
      out.write("         <div class=\"inner_breadcrumb  ml-4\">\r\n");
      out.write("            <ul class=\"short_ls\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"index.jsp\">Home</a>\r\n");
      out.write("                  <span>/ /</span>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"flip\">HOD LOGIN</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- //short-->\r\n");
      out.write("   \r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write(" <div class=\"col-lg-12 col-md-12\">\r\n");
      out.write("         \r\n");
      out.write("\t<div class=\"login_section\" id=\"panel\">\r\n");
      out.write("\t\t<div class=\"message warning\">\r\n");
      out.write("\t\t\t<div class=\"inset agile\">\r\n");
      out.write("\t\t\t\t<div class=\"sap_tabs w3ls-tabs\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 if(request.getAttribute("Message") != null) { 
      out.write("\r\n");
      out.write("    \t\t\t\t<b><h3 style=\"color: red\">");
      out.print( request.getAttribute("Message") );
      out.write("</h3></b>\r\n");
      out.write("   \t \t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"horizontalTab\" style=\"display: block; width: 100%; margin: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"resp-tabs-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"resp-tab-item\" aria-controls=\"tab_item-0\" role=\"tab\"><span>HOD Sign in</span></li> \r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"resp-tab-item\" aria-controls=\"tab_item-1\" role=\"tab\"><label>/</label><span>HOD Sign up</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert-close\"> </div> \r\n");
      out.write("\t\t\t\t\t<div class=\"resp-tabs-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" aria-labelledby=\"tab_item-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-agileits-top\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"hodlogin\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Email-ID </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" name = \"emailid\" id=\"emailid\" required=\"\" autofocus=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Password</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name = \"password\" id=\"password\" maxlength=\"20\" required=\"\" autofocus=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"brand\" onclick=\"showpassword()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand\"><span></span>show password</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Designation</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name = \"desi\" id = \"desi\">  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"hod\">H.O.D</option>\r\n");
      out.write("        \t\t\t\t\t\t\t</select>\r\n");
      out.write("        \t\t\t\t\t\t\t<input type=\"checkbox\" id=\"brand1\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand1\"><span></span> Remember me ?</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"SIGN IN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-agileits-bottom\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<h2><a href=\"frgtpass.jsp\">Forgot password?</a></h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" aria-labelledby=\"tab_item-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-agileits-top sign-up\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"staffregistration\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>HOD Name </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"staffname\" id=\"staffname1\" maxlength=\"20\" required=\"\" autofocus=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--  <p id=\"validationMessage\" style=\"color: red; font-weight: bold;\"></p>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Email-ID </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" name = \"email\" id=\"email\" required=\"\" autofocus=\"\" autocomplete=\"off\" onblur=\"ajaxFunction()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Password</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name = \"password\" id=\"password1\" maxlength=\"20\" required=\"\" autofocus=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"brand2\" onclick=\"showpassword1()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand2\"><span></span>show password</label> \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Address</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name = \"address\" id = \"address\" maxlength = \"50\" required=\"\" autofocus=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Date of Joining</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" name = \"doj\" id=\"doj\" required=\"required\" autofocus=\"autofocus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Mobile-No</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"number\" name = \"mob\" id = \"mob\" maxlength=\"10\" required=\"required\" autofocus=\"autofocus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Department</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name = \"dept\" id = \"dept\">  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"cse\">CSE</option>\r\n");
      out.write("        \t\t\t\t\t\t\t<option value=\"it\">IT</option>  \r\n");
      out.write("        \t\t\t\t\t\t\t<option value=\"me\">ME</option>\r\n");
      out.write("        \t\t\t\t\t\t\t<option value=\"ece\">ECE</option>\r\n");
      out.write("        \t\t\t\t\t\t\t<option value=\"ee\">EE</option>\r\n");
      out.write("        \t\t\t\t\t\t\t<option value=\"ce\">CE</option>\r\n");
      out.write("        \t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Designation</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name = \"desi\" id = \"desi\">  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"hod\">H.O.D</option>  \r\n");
      out.write("        \t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"brand3\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand3\"><span></span>I accept the terms use</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"submitForm\" value=\"SIGN UP\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t \r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"right-section-w3ls\"> </div>\r\n");
      out.write("\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t</div>\t</div> </div> </div> </div>\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<!-- //LOGIN & REGISTRATION AREA -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("<!--comments-->\r\n");
      out.write("      <section class=\"comments py-lg-4 py-md-3 py-sm-3 py-3\">\r\n");
      out.write("         <div class=\"container py-lg-5 py-md-4 py-sm-4 py-3\">\r\n");
      out.write("            <div class=\"fun-hedder-up\">\r\n");
      out.write("               <h6>COLLEGE INVENTORY SYSTEM</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <!--//comments-->\r\n");
      out.write("\t<!--Footer -->\r\n");
      out.write("      <section class=\"py-lg-4 py-md-3 py-sm-3 py-3\">\r\n");
      out.write("        \r\n");
      out.write("      </section>\r\n");
      out.write("      <section class=\"images-position-grid\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row imgs-both-side\">\r\n");
      out.write("               <div class=\"col-lg-6 col-md-6 col-sm-6 img-first-left\">\r\n");
      out.write("                  <h5>TECHNO INDIA GROUP</h5>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-6 col-md-6 col-sm-6 img-second-left\">\r\n");
      out.write("                  <h5>TECHNO INDIA GROUP</h5>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <footer class=\"buttom-footer py-lg-4 py-md-3 py-sm-3 py-3\">\r\n");
      out.write("         <section>\r\n");
      out.write("            <div class=\"container py-lg-5 py-md-5 py-sm-4 py-4\">\r\n");
      out.write("               <div class=\"\">\r\n");
      out.write("                  <div class=\"row footer-agile-grids \">\r\n");
      out.write("                     <div class=\"col-lg-4 col-md-4 col-sm-12 wthree-left-right\">\r\n");
      out.write("                        <h4 class=\"pb-lg-3 pb-3\">Nav Links</h4>\r\n");
      out.write("                        <nav class=\"border-line\">\r\n");
      out.write("                           <ul class=\"nav flex-column\">\r\n");
      out.write("                              <li class=\"nav-item active\">\r\n");
      out.write("                                 <a class=\"nav-link\" href=\"index.jsp\">HOME <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"about.jsp\" class=\"nav-link\">ABOUT</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"stafflogreg.jsp\" class=\"nav-link\">STAFF_LOGIN</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"hodlogreg.jsp\" class=\"nav-link\">HOD_LOGIN</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"nav-item\">\r\n");
      out.write("                                 <a href=\"admnlog.jsp\" class=\"nav-link\">ADMIN_LOGIN</a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"wthree-left-right col-lg-4 col-md-4 col-sm-12\">\r\n");
      out.write("                        <h4 class=\"pb-lg-3 pb-3\">Get In Touch</h4>\r\n");
      out.write("                        <div class=\"wls-hours-list\">\r\n");
      out.write("                           <ul>\r\n");
      out.write("                              <li class=\"d-flex\">Monday-Friday<span class=\"time ml-auto\"> 6:00am-11:00pm</span></li>\r\n");
      out.write("                              <li class=\"d-flex\">Saturday-Sunday <span class=\"time ml-auto\">6:00am-11:00pm</span></li> \r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </section>\r\n");
      out.write("         <div class=\"copy-agile-right text-center\">\r\n");
      out.write("            <p>© 2019 ANODITE CELL. All Rights Reserved | Design by <a href=\"#\" target=\"_blank\">INVENTORY</a></p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("      <!-- //Footer -->\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- //OnScroll-Number-Increase-JavaScript -->  \r\n");
      out.write("      <!-- start-smoth-scrolling -->\r\n");
      out.write("      <script src=\"js/move-top.js\"></script>\r\n");
      out.write("      <script src=\"js/easing.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("         jQuery(document).ready(function ($) {\r\n");
      out.write("         \t$(\".scroll\").click(function (event) {\r\n");
      out.write("         \t\tevent.preventDefault();\r\n");
      out.write("         \t\t$('html,body').animate({\r\n");
      out.write("         \t\t\tscrollTop: $(this.hash).offset().top\r\n");
      out.write("         \t\t}, 900);\r\n");
      out.write("         \t});\r\n");
      out.write("         });\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("\t  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
